name: Nightly Release

on:
  schedule:
    - cron: "30 15 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate tag and title
        run: |
          echo "TAG=n_$(date +'%d-%m-%Y')" >> $GITHUB_ENV
          echo "TITLE=[Nightly] n$(date +'%d-%m-%Y')" >> $GITHUB_ENV

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$TAG" \
            --title "$TITLE" \
            --notes "Automated nightly build." \
            --prerelease \
            --target main
